- hosts: redis
  become: true
  become_user: root
  roles:
    - epel
    - redis

- hosts: mysql
  become: true
  become_user: root
  vars_files:
    - vars/mysql.yml
  roles:
    - { role: geerlingguy.mysql }

- hosts: fronts
  become: true
  become_user: root
  vars_files:
    - vars/ansistrano.yml
  roles:
    - epel
    - php
    - apache
    - composer
    - git
    - hosts
    - seboolean
    - { role: carlosbuenosvinos.ansistrano-deploy }
    - blog-database