- name: Deploy blog at amazon
  hosts: webservers
  become: true
  become_user: root
  vars_files:
    - vars/ansistrano.yml
    - vars/mysql.yml
  roles:
    - epel
    - php
    - apache
    - composer
    - git
    - hosts
    - seboolean
    - { role: geerlingguy.mysql }
    - { role: carlosbuenosvinos.ansistrano-deploy }
    - blog-database