Performance\Domain\Article:
  type: entity
  repositoryClass: \Performance\Infrastructure\Database\DoctrineArticleRepository
  table: articles
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: text
    content:
      type: text
    tags:
      type: text
    created_at:
      type: integer
  manyToOne:
    author:
      targetEntity: Performance\Domain\Author
      cascade: ["persist"]
      fetch: EAGER
      joinColumn:
        name: author_id
        referencedColumnName: id